-- This script initially sets up the tables for the "config" schema

CREATE TABLE config.owner
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);


CREATE TABLE config.case_state
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);

CREATE TABLE config.severity_level
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);


CREATE TABLE config.device_health
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255),
    color_code VARCHAR(9) -- hexCode with '#' included
);

CREATE TABLE config.event_type
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);


