-- This script initially sets up the tables for the "data" schema

CREATE TABLE data.case
(

);
CREATE TABLE data.event
(

);
CREATE TABLE data.netplan_group
(

);
CREATE TABLE data.host
(

);
CREATE TABLE data.team
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255),
    colorCode VARCHAR(9) -- hexCode with '#' included
);
