services:
  postgres:
    image: postgres:16-alpine
    container_name: cyber-journaling-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cyber-journaling
      POSTGRES_USER: cyber-journaling
      POSTGRES_PASSWORD: cyber-journaling
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyber-journaling -d cyber-journaling"]
      interval: 5s
      timeout: 5s
      retries: 10

# TODO: add container for application and setup for it
volumes:
  postgres_data:
