#services:
#  postgres:
#    image: postgres:16-alpine
#    container_name: cyber-journal-postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: journaling
#      POSTGRES_USER: journaling
#      POSTGRES_PASSWORD: journaling
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U journaling -d journaling"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#volumes:
#  postgres_data:
