-- This script initially sets up the tables for the "data" schema

-- CASE/EVENT
CREATE TABLE data.journal_case
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id       INTEGER REFERENCES config.team (id),
    case_state_id INTEGER REFERENCES config.case_state (id),
    owner_id      INTEGER REFERENCES config.owner (id),
    title         VARCHAR(255),
    details       VARCHAR(2048)
);

CREATE TABLE data.journal_event
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity_level_id INTEGER REFERENCES config.severity_level (id),
    device_health_id  INTEGER REFERENCES config.device_health (id),
    event_type_id     INTEGER REFERENCES config.event_type (id),
    case_id           INTEGER REFERENCES data.journal_case (id),
    timestamp         TIMESTAMP,
    title             VARCHAR(255),
    details           VARCHAR(2048)
);


-- NETPLAN
CREATE TABLE data.netplan_group
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    INTEGER REFERENCES config.team (id) NOT NULL,
    name       VARCHAR(255)                        NOT NULL,
    color_code VARCHAR(9) -- hexCode with '#' included
);

CREATE TABLE data.host
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    netplan_group_id      INTEGER REFERENCES data.netplan_group (id) NOT NULL,
    name                  VARCHAR(255)                               NOT NULL,
    ip_description        VARCHAR(1024)                              NOT NULL, -- holds ip address/es and subnets
    description           VARCHAR(2048),
    background_color_code VARCHAR(9)                                           -- hexCode with '#' included
);

CREATE TABLE data.service
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id     INTEGER REFERENCES data.host (id) NOT NULL,
    name        VARCHAR(255)                      NOT NULL,
    description VARCHAR(2048),
    port        VARCHAR(5)                        NOT NULL, -- port that the service runs on
    icon_name   VARCHAR(255),                               -- filename of svg in /resources/icons
    exposed     BOOLEAN DEFAULT TRUE
);

-- Many-To-Many Relation
CREATE TABLE data.journal_events_services
(
    event_id   INTEGER REFERENCES data.journal_event,
    service_id INTEGER REFERENCES data.service,
    PRIMARY KEY (event_id, service_id)
);